export const legendTopConfig = {
	gaoyaPoints: {
		label: '高压管网',
		// icon: 'icon-gaoya',
		visible: true,
		layer: 'line',
		color: '#41FFBB',
	},
	zhongyaPoints: {
		label: '中压管网',
		// icon: 'icon-cigaoya',
		visible: true,
		layer: 'line',
		color: '#D736FF',
	},
	diyaPoints: {
		label: '低压管网',
		// icon: 'icon-zhongya',
		visible: true,
		layer: 'line',
		color: '#364AFF',
	},
	doorStationPoints: {
		label: '门站',
		icon: 'icon-menzhan',
		visible: true,
		layer: 'icon',
	},
	emergencyStationPoints: {
		label: '应急站',
		icon: 'icon-a-yingjizhan1',
		visible: true,
		layer: 'icon',
	},
	gasFillPoints: {
		label: '加气站',
		icon: 'icon-jiaqizhan',
		visible: true,
		layer: 'icon',
	},
	highPressureAdjustPoints: {
		label: '高中压调压站',
		icon: 'icon-gaozhongyatiaoyazhan',
		visible: true,
		layer: 'icon',
	},
	middlePressureAdjustPoints: {
		label: '中低压调压站',
		icon: 'icon-zhongdiyatiaoyazhan',
		visible: false,
		layer: 'icon',
	},
	monitorPoints: {
		label: '压力监测点',
		icon: 'icon-yalijiancedian',
		visible: false,
		layer: 'icon',
	},
	leakAlarmPoints: {
		label: '泄漏报警点',
		icon: 'icon-xieloubaojingdian',
		visible: true,
		layer: 'icon',
	},
	hiddenTroublePoints: {
		label: '巡检隐患点',
		icon: 'icon-xunjianyinhuandian',
		visible: true,
		layer: 'icon',
	},
	destructionPoints: {
		label: '第三方破坏',
		icon: 'icon-disanfangpohuai',
		visible: true,
		layer: 'icon',
	},
	lookAfterPoints: {
		label: '工地看护点',
		icon: 'icon-gongdikanhudian',
		visible: true,
		layer: 'icon',
	},
	ScramblePoints: {
		label: '抢维事件',
		icon: 'icon-qiangweishijian',
		visible: true,
		layer: 'icon',
	},
	technologyAlarmPoints: {
		label: '工艺报警',
		icon: 'icon-gongyibaojing',
		visible: true,
		layer: 'icon',
	},
	repairCarPoints: {
		label: '巡检抢修车',
		icon: 'icon-xunjianqiangxiuche',
		visible: true,
		layer: 'icon',
	},
	repairPeoplePoints: {
		label: '巡检抢修员',
		icon: 'icon-xunjianqiangxiuyuan',
		visible: true,
		layer: 'icon',
	},
	videoMonitorPoints: {
		label: '视频监控',
		icon: 'icon-shipinjiankong',
		visible: true,
		layer: 'icon',
	},
	managePoints: {
		label: '运行管理站',
		icon: 'icon-yunhangguanlizhan',
		visible: true,
		layer: 'icon',
	},
	hiddenTroubleHeatPoints: {
		label: '巡检隐患热力',
		icon: 'icon-relitu',
		visible: true,
		layer: 'icon',
	},
	repairHeatPoints: {
		label: '抢维修热力',
		icon: 'icon-relitu',
		visible: true,
		layer: 'icon',
	},
}
export const legendBottomConfig = {
	companyPoints: {
		label: '公司',
		icon: 'icon-zigongsi',
		visible: true,
		layer: 'icon',
	},
	serviceNetworkPoints: {
		label: '服务网点',
		icon: 'icon-fuwuwangdian-01',
		visible: true,
		layer: 'line',
		color: '#C85041',
	},
	workOrderTaskPoints: {
		label: '工单任务点',
		icon: 'icon-gongdanrenwu',
		visible: true,
		layer: 'line',
		color: '#00FFCF',
	},
	iotAlarmPoints: {
		label: '物联报警',
		icon: 'icon-yijiwulianbaojing',
		visible: true,
		layer: 'line',
		color: '#4378FF',
	},
	householdPoints: {
		label: '居民户',
		icon: 'icon-juminhu',
		visible: true,
		layer: 'icon',
	},
	businessPoints: {
		label: '工商户',
		icon: 'icon-gongshanghu',
		visible: true,
		layer: 'icon',
	},
	customerHeatPoints: {
		label: '客户热力',
		icon: 'icon-relitu',
		visible: true,
		layer: 'icon',
	},
	gasHeatPoints: {
		label: '用气量热力',
		icon: 'icon-relitu',
		visible: true,
		layer: 'icon',
	},
	billHeatPoints: {
		label: '欠费热力',
		icon: 'icon-relitu',
		visible: false,
		layer: 'icon',
	},
	workOrderHeatPoints: {
		label: '工单热力',
		icon: 'icon-relitu',
		visible: false,
		layer: 'icon',
	},
	checkHeatPoints: {
		label: '安检隐患热力',
		icon: 'icon-relitu',
		visible: true,
		layer: 'icon',
	},
}

export const videoUrl = 'https://my.eslink.com/home?id=01671901&parentId=0167'
